import { backgroundData } from '../database/background.js';
import { battlefieldData } from '../database/battlefield.js';
import { enemiesData } from '../database/enemies.js';
import { gedo_ninpoData } from '../database/gedo_ninpo.js';
import { mysteryData } from '../database/mystery.js';
import { ninpoData } from '../database/ninpo.js';
import { ougi_kaihatsuData } from '../database/ougi_kaihatsu.js';
import { personaData } from '../database/persona.js';
import { ritual_ninpoData } from '../database/ritual_ninpo.js';
import { variantData } from '../database/variant.js';
import { yoma_weaponsData } from '../database/yoma_weapons.js';
import { yuigamiData } from '../database/yuigami.js';
import { CategoryConfig, DataRow } from './types';

const asRows = (data: unknown[]): DataRow[] => data as DataRow[];

export const categories: CategoryConfig[] = [
  {
    key: '战场',
    aliases: ['战场', '战场表', 'battlefield', '战地'],
    data: asRows(battlefieldData),
    primaryField: '名字',
    searchFields: ['名字', '效果（表）', '效果（里）'],
    tagFields: [],
    categoryFields: [],
    listItemFields: ['效果（表）'],
    detailFields: ['序号', '名字', '效果（表）', '效果（里）'],
    shortcutCommandNames: ['查战场', '查战场表'],
    plainPrefixes: ['查战场', '查战场表'],
    globalOrder: 1,
  },
  {
    key: '变调',
    aliases: ['变调', '异常状态', '状态', 'variant'],
    data: asRows(variantData),
    primaryField: '名字',
    searchFields: ['名字', '描述'],
    tagFields: [],
    categoryFields: [],
    listItemFields: ['描述'],
    detailFields: ['序号', '名字', '描述'],
    shortcutCommandNames: ['查变调', '查状态', '查异常状态'],
    plainPrefixes: ['查变调', '查状态', '查异常状态'],
    globalOrder: 2,
  },
  {
    key: '忍法',
    aliases: ['忍法', 'ninpo', 'np', '忍術', '忍术'],
    data: asRows(ninpoData),
    primaryField: '名字',
    searchFields: ['名字', '效果', '描述', '备注', '指定特技'],
    tagFields: ['分支', '类别', '指定特技'],
    categoryFields: [
      { field: '距离', valueType: 'string' },
      { field: '花费', valueType: 'string' },
    ],
    listItemFields: ['分支', '类别'],
    detailFields: [
      '序号',
      '分支',
      '名字',
      '类别',
      '距离',
      '花费',
      '指定特技',
      '描述',
      '效果',
      '备注',
    ],
    shortcutCommandNames: [
      '查忍法',
      '查忍术',
      '查忍術',
      '查NP',
      '查np',
      '查ninpo',
    ],
    plainPrefixes: ['查忍法', '查忍术', '查忍術', '查NP', '查np', '查ninpo'],
    globalOrder: 3,
  },
  {
    key: '背景',
    aliases: ['背景', 'bg', '长处', '弱点'],
    data: asRows(backgroundData),
    primaryField: '名字',
    searchFields: ['名字', '说明', '描述'],
    tagFields: ['类型', '修得限制'],
    categoryFields: [{ field: '功绩点', valueType: 'number' }],
    listItemFields: ['类型', '功绩点'],
    detailFields: [
      '序号',
      '类型',
      '名字',
      '功绩点',
      '修得限制',
      '说明',
      '描述',
    ],
    shortcutCommandNames: ['查背景', '查BG', '查bg', '查长处', '查弱点'],
    plainPrefixes: ['查背景', '查BG', '查bg', '查长处', '查弱点'],
    globalOrder: 4,
  },
  {
    key: '奥义开发',
    aliases: ['奥义开发', '奥義開発', '奥义改造', '奥义强化', 'ougi'],
    data: asRows(ougi_kaihatsuData),
    primaryField: '名字',
    searchFields: ['名字', '说明', '描述', '类型', '使用范围', '限定流派'],
    tagFields: ['类型', '使用范围', '限定流派'],
    categoryFields: [],
    listItemFields: ['类型', '使用范围'],
    detailFields: [
      '序号',
      '类型',
      '名字',
      '使用范围',
      '限定流派',
      '说明',
      '描述',
    ],
    shortcutCommandNames: [
      '查奥义开发',
      '查奥义',
      '查奥義',
      '查奥义强化',
      '查Ougi',
    ],
    plainPrefixes: [
      '查奥义开发',
      '查奥义',
      '查奥義',
      '查奥义强化',
      '查ougi',
      '查Ougi',
    ],
    globalOrder: 5,
  },
  {
    key: '人格假面',
    aliases: ['人格假面', '人格', 'persona', '真实', '真相'],
    data: asRows(personaData),
    primaryField: '名字',
    searchFields: ['名字', '说明', '描述'],
    tagFields: ['类型'],
    categoryFields: [],
    listItemFields: ['类型'],
    detailFields: ['序号', '类型', '名字', '说明', '描述'],
    shortcutCommandNames: ['查人格假面', '查人格', '查Persona', '查真实'],
    plainPrefixes: ['查人格假面', '查人格', '查persona', '查Persona', '查真实'],
    globalOrder: 6,
  },
  {
    key: '惟神',
    aliases: ['惟神', '神格', '御神', 'yuigami'],
    data: asRows(yuigamiData),
    primaryField: '名字',
    searchFields: ['名字', '效果', '描述', '指定特技'],
    tagFields: ['指定特技'],
    categoryFields: [],
    listItemFields: ['指定特技'],
    detailFields: ['序号', '名字', '指定特技', '效果', '描述'],
    shortcutCommandNames: ['查惟神', '查神格', '查御神'],
    plainPrefixes: ['查惟神', '查神格', '查御神'],
    globalOrder: 7,
  },
  {
    key: '敌人',
    aliases: ['敌人', '敌方', '敌对', '敌人数据', 'enemy', 'enemies'],
    data: asRows(enemiesData),
    primaryField: '名字',
    searchFields: [
      '名字',
      '概述',
      '得意分野与特技',
      '持有的忍法与人格假面',
      '其他',
      '分类',
      '出处',
    ],
    tagFields: ['分类', '出处', '威胁度'],
    categoryFields: [
      { field: '生命力', valueType: 'number' },
      { field: '威胁度', valueType: 'number' },
    ],
    listItemFields: ['分类', '威胁度'],
    detailFields: [
      '序号',
      '分类',
      '名字',
      '出处',
      '概述',
      '生命力',
      '威胁度',
      '忍具',
      '奥义数量',
      '得意分野与特技',
      '持有的忍法与人格假面',
      '其他',
    ],
    shortcutCommandNames: ['查敌人', '查敌方', '查敌对', '查Enemy'],
    plainPrefixes: ['查敌人', '查敌方', '查敌对', '查enemy', '查Enemy'],
    globalOrder: 8,
  },
  {
    key: '妖魔武器',
    aliases: ['妖魔武器', '妖武', '武器', '妖魔', 'ymwq'],
    data: asRows(yoma_weaponsData),
    primaryField: '名字',
    searchFields: ['名字', '说明'],
    tagFields: [],
    categoryFields: [{ field: '维持功绩点', valueType: 'number' }],
    listItemFields: ['维持功绩点'],
    detailFields: ['序号', '名字', '维持功绩点', '说明'],
    shortcutCommandNames: ['查妖魔武器', '查妖武'],
    plainPrefixes: ['查妖魔武器', '查妖武'],
    globalOrder: 9,
  },
  {
    key: '仪式忍法',
    aliases: ['仪式忍法', '仪式', '仪忍', 'ritual', '仪式法'],
    data: asRows(ritual_ninpoData),
    primaryField: '名字',
    searchFields: [
      '名字',
      '效果',
      '描述',
      '仪式1',
      '仪式2',
      '仪式3',
      '仪式4',
      '仪式5',
      '仪式6',
    ],
    tagFields: [],
    categoryFields: [
      { field: '韵度', valueType: 'number' },
      { field: '初期念度', valueType: 'number' },
      { field: '额外念度', valueType: 'number' },
    ],
    listItemFields: ['韵度', '初期念度'],
    detailFields: [
      '序号',
      '名字',
      '韵度',
      '初期念度',
      '额外念度',
      '描述',
      '效果',
      '仪式1',
      '仪式2',
      '仪式3',
      '仪式4',
      '仪式5',
      '仪式6',
    ],
    shortcutCommandNames: ['查仪式忍法', '查仪式', '查仪忍'],
    plainPrefixes: ['查仪式忍法', '查仪式', '查仪忍'],
    globalOrder: 10,
  },
  {
    key: '谜团',
    aliases: ['谜团', '謎團', 'mystery', '谜'],
    data: asRows(mysteryData),
    primaryField: '名字',
    searchFields: [
      '名字',
      '描述',
      '威胁度',
      '效果',
      '解除特技',
      '计划判定',
      '种类',
    ],
    tagFields: ['种类', '威胁度'],
    categoryFields: [],
    listItemFields: ['种类', '威胁度'],
    detailFields: [
      '序号',
      '种类',
      '名字',
      '描述',
      '威胁度',
      '解除特技',
      '计划判定',
      '效果',
    ],
    shortcutCommandNames: ['查谜团', '查謎團', '查谜'],
    plainPrefixes: ['查谜团', '查謎團', '查谜', '查mystery'],
    globalOrder: 11,
  },
  {
    key: '外道忍法',
    aliases: ['外道忍法', '外道', '外道忍', 'gedo', '邪忍'],
    data: asRows(gedo_ninpoData),
    primaryField: '名字',
    searchFields: [
      '名字',
      '效果',
      '描述',
      '來源',
      '来源',
      '類別',
      '距离',
      '距離',
      '花費',
      '指定特技',
    ],
    tagFields: ['來源', '来源', '類別', '距离', '距離'],
    categoryFields: [],
    listItemFields: ['來源', '来源', '類別'],
    detailFields: [
      '序号',
      '來源',
      '来源',
      '名字',
      '類別',
      '距离',
      '距離',
      '花費',
      '指定特技',
      '效果',
      '描述',
    ],
    shortcutCommandNames: ['查外道忍法', '查外道', '查邪忍', '查Gedo'],
    plainPrefixes: ['查外道忍法', '查外道', '查邪忍', '查gedo', '查Gedo'],
    globalOrder: 12,
  },
];

export const aliasMap: Map<string, CategoryConfig> = (() => {
  const map = new Map<string, CategoryConfig>();
  categories.forEach((category) => {
    category.aliases.forEach((alias) => {
      map.set(alias.toLowerCase(), category);
    });
  });
  return map;
})();

export const plainPrefixEntries: Array<{ prefix: string; category: CategoryConfig }> = categories.flatMap((category) =>
  (category.plainPrefixes ?? []).map((prefix) => ({ prefix, category }))
);

export const sortedCategoriesForGlobalSearch = [...categories].sort((a, b) => a.globalOrder - b.globalOrder);
